### ISSUE TITLE
Add Dark and Light Theme 

### ISSUE THREAD

**Issue by karmveershubham** [karmveershubham/Gemini#1]
Create a toggle for light and dark theme in the app

**Comment by Yashop181** [comment]
I have added the light and dark theme toggle functionality and pushed the code to the darklightmode branch. Please review the code.

**Comment by Yashop181** [comment]
Hello there! I'm glad to inform you that I've successfully implemented the dark mode toggle for the entire page, including sidebar, cards and input fields. Thank you for your assistance!

**Comment by karmveershubham** [comment]
DONE
